# -*- coding: utf-8 -*-
"""PredictiveAlzheimer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tp80S-aAHArkmPBgJBvNBCHa3VeVY4LY
"""

import pandas as pd
import numpy as np

df = pd.read_excel('alzheimer.xlsx')
df.columns = ['Age','Gender','Etchinicity','EducationLevel','BMI','Smoking','AlcoholConsumption','PhysicalActivity','DietQuality','SleepQuality','FamilyHistoryAlzheimers','CardiovascularDisease','Diabetes','Depression','HeadInjury','Hypertension','SystolicBP','DiastolicBP','CholesterolTotal','CholesterolLDL','CholesterolHDL','CholesterolTriglycerides','MMSE','FunctionalAssessment','MemoryComplaints','BehavioralProblems','ADL','Confusion','Disorientation','PersonalityChanges','DifficultyCompletingTasks','Forgetfulness','Diagnosis']
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')
# 'RdBu_r', 'BrBG_r', & PuOr_r are other good diverging colormaps

import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Define independent (X) and dependent (y) variables
X = df[['Age', 'Gender', 'Etchinicity', 'EducationLevel','BMI','Smoking','AlcoholConsumption','PhysicalActivity','DietQuality','SleepQuality','FamilyHistoryAlzheimers','CardiovascularDisease','Diabetes','Depression','HeadInjury','Hypertension','SystolicBP','DiastolicBP','CholesterolTotal','CholesterolLDL','CholesterolHDL','CholesterolTriglycerides','MMSE','FunctionalAssessment','MemoryComplaints','BehavioralProblems','ADL','Confusion','Disorientation','PersonalityChanges','DifficultyCompletingTasks','Forgetfulness']]
y = df['Diagnosis']

# Check if y is categorical, if not convert it to binary (0 or 1)
if y.dtype != 'int' and y.dtype != 'float':
    y = y.astype('category').cat.codes  # Convert categorical target to numeric

# Drop columns with zero variance (constant values)
X = X.loc[:, X.nunique() > 1]

# Check for highly correlated features
correlation_matrix = X.corr().abs()
high_correlation = (correlation_matrix > 0.9).sum() > 1
X = X.loc[:, ~high_correlation]  # Drop highly correlated features

# Add a constant (intercept) for statsmodels
X = sm.add_constant(X)

# Split into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features for sklearn
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic regression using scikit-learn
sklearn_model = LogisticRegression()
sklearn_model.fit(X_train_scaled, y_train)

# Predictions
y_pred = sklearn_model.predict(X_test_scaled)

# Evaluate model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred))
def plot_confusion_matrix(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()
plot_confusion_matrix(y_test, y_pred)

# Logistic regression using statsmodels (without scaling)
try:
    sm_model = sm.Logit(y_train, X_train).fit()
    print(sm_model.summary())
except np.linalg.LinAlgError:
    print("Error: Singular matrix detected. Check for multicollinearity.")

import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
# Define independent (X) and dependent (y) variables
X = df[['MMSE','FunctionalAssessment','MemoryComplaints','BehavioralProblems','ADL']]
y = df['Diagnosis']

# Check if y is categorical, if not convert it to binary (0 or 1)
if y.dtype != 'int' and y.dtype != 'float':
    y = y.astype('category').cat.codes  # Convert categorical target to numeric

# Drop columns with zero variance (constant values)
X = X.loc[:, X.nunique() > 1]

# Check for highly correlated features
correlation_matrix = X.corr().abs()
high_correlation = (correlation_matrix > 0.9).sum() > 1
X = X.loc[:, ~high_correlation]  # Drop highly correlated features

# Add a constant (intercept) for statsmodels
X = sm.add_constant(X)

# Split into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features for sklearn (but NOT for statsmodels)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic regression using scikit-learn
sklearn_model = LogisticRegression()
sklearn_model.fit(X_train_scaled, y_train)

# Predictions
y_pred = sklearn_model.predict(X_test_scaled)

# Evaluate model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred))
def plot_confusion_matrix(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()
plot_confusion_matrix(y_test, y_pred)

# Logistic regression using statsmodels (without scaling)
try:
    sm_model = sm.Logit(y_train, X_train).fit()
    print(sm_model.summary())
except np.linalg.LinAlgError:
    print("Error: Singular matrix detected. Check for multicollinearity.")